---
apiVersion: v1
kind: Service
metadata:
  name: alpine-nettools2-ssh
  labels:
    app: alpine-nettools2
    tier: app
spec:
  ports:
  - port: 2200
    targetPort: 22
  selector:
    tier: app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alpine-nettools2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine-nettools2
        tier: app
    spec:
      containers:
      - name: alpine-nettools2
        image: raesene/alpine-nettools
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        imagePullPolicy: Always


